BIXIE: bixiewriter.c File Reference
bixiewriter.c File Reference
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include "bixiewriter.h"
#include "symboltable.h"
#include "ast.h"
#include "encoding.h"
#include "compiler.h"
Defines
#define BIXIE_BUFFER_SIZE 209715200
Functions
static void copyToBixieBuffer (byte *encodingBuffer, int encodingLength, byte **bixieBuffer, int *bufferLength, int *allocated)
static void encodeTrailingSequence (element_t *element, int listSize, byte **bixieBuffer, int *bufferLength, int *allocated)
static void encodeAttributes (symbolTable_t *symbolTable, byte **bixieBuffer, int *bufferLength, int *allocated, element_t *element, elementTable_t *elementTable)
static void encodeContent (symbolTable_t *symbolTable, byte **bixieBuffer, int *bufferLength, int *allocated, element_t *element, elementTable_t *elementTable)
static void prettyPrint (element_t *ast)
static void printElement (element_t *element, int depth)
static freeASTElement (element_t *element)
void encodeASTToBIXIE (element_t *ast, byte **bixieBuffer, int *bufferLength, symbolTable_t symbolTable)
void encodeElement (symbolTable_t *symbolTable, byte **bixieBuffer, int *bufferLength, int *allocated, element_t *element, element_t *leftSibling)
Define Documentation
#define BIXIE_BUFFER_SIZE 209715200
Referenced by encodeASTToBIXIE().
Function Documentation
static void copyToBixieBuffer (byte * encodingBuffer, int encodingLength, byte ** bixieBuffer, int * bufferLength, int * allocated) [static]
Copies data to the BIXIE buffer
Parameters:
encodingBuffer The buffer from which to copy
encodingLength The length of the data to be copied
bixieBuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
allocated The length of the allocated buffer prior to the element
Returns:
Referenced by encodeAttributes(), encodeContent(), encodeElement(), and encodeTrailingSequence().
void encodeASTToBIXIE (element_t * ast, byte ** bixieBuffer, int * bufferLength, symbolTable_t symbolTable)
Traverses an given AST and encodes it to BIXIE
Parameters:
ast The AST to encode into BIXIE
bixieBuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
symbolTable The symbolTable associated with BIXIE
Returns:
Referenced by encodeXMLToBIXIE().
static void encodeAttributes (symbolTable_t * symbolTable, byte ** bixieBuffer, int * bufferLength, int * allocated, element_t * element, elementTable_t * elementTable) [static]
Encode attributes of an element
Parameters:
symbolTable The symbolTable associated with BIXIE
bixieBuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
allocated The length of the allocated buffer prior to the element
element The element containing the attributes
elementTable The single entry of an element from the symbol table
Returns:
Referenced by encodeElement().
static void encodeContent (symbolTable_t * symbolTable, byte ** bixieBuffer, int * bufferLength, int * allocated, element_t * element, elementTable_t * elementTable) [static]
Encode the content of an element
Parameters:
symbolTable The symbolTable associated with BIXIE
bixieBuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
allocated The length of the allocated buffer prior to the element
element The element containing the content
elementTable The single entry of an element from the symbol table
Returns:
Referenced by encodeElement().
void encodeElement (symbolTable_t * symbolTable, byte ** bixieBuffer, int * bufferLength, int * allocated, element_t * element, element_t * leftSibling)
Encodes a single element into BIXIE and appends the encoded element to the buffer
Parameters:
symbolTable The symbolTable associated with BIXIE
bixiebuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
allocated The length of the allocated buffer prior to the element
element The element to be encoded
leftSibling The left sibling of the element to be encoded
Returns:
Referenced by encodeASTToBIXIE().
static void encodeTrailingSequence (element_t * element, int listSize, byte ** bixieBuffer, int * bufferLength, int * allocated) [static]
Encode trailing zeros in a sequence of elements
Parameters:
element The element containing the sequence
listSize The size of the list of elements in the sequence
bixieBuffer The buffer intended for the encoded BIXIE
bufferLength The length of the bixieBuffer parameter
allocated The length of the allocated buffer prior to the element
Returns:
Referenced by encodeASTToBIXIE().
static freeASTElement (element_t * element) [static]
Parameters:
element The element of the AST to be freed
Returns:
Referenced by encodeASTToBIXIE().
static void prettyPrint (element_t * ast) [static]
Traverses the AST in a left child->right sibling->parent loop. At each element it prints the values of the element
Parameters:
ast The AST to encode into BIXIE
Returns:
Referenced by encodeASTToBIXIE().
static void printElement (element_t * element, int depth) [static]
Prints the values of a given element and indents the text based on a depth
Parameters:
element The element to be printed
depth The current depth of the print
Returns:
Referenced by prettyPrint().