BIXIE: cJSON.h File Reference
cJSON.h File Reference
Data Structures
struct cJSON
struct cJSON_Hooks
Defines
#define cJSON_False 0
#define cJSON_True 1
#define cJSON_NULL 2
#define cJSON_Number 3
#define cJSON_String 4
#define cJSON_Array 5
#define cJSON_Object 6
#define cJSON_IsReference 256
#define cJSON_AddNullToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateNull())
#define cJSON_AddTrueToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateTrue())
#define cJSON_AddFalseToObject(object, name) cJSON_AddItemToObject(object, name, cJSON_CreateFalse())
#define cJSON_AddNumberToObject(object, name, n) cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))
#define cJSON_AddStringToObject(object, name, s) cJSON_AddItemToObject(object, name, cJSON_CreateString(s))
Typedefs
typedef struct cJSON cJSON
typedef struct cJSON_Hooks cJSON_Hooks
Functions
void cJSON_InitHooks (cJSON_Hooks *hooks)
cJSON * cJSON_Parse (const char *value)
char * cJSON_Print (cJSON *item)
char * cJSON_PrintUnformatted (cJSON *item)
void cJSON_Delete (cJSON *c)
int cJSON_GetArraySize (cJSON *array)
cJSON * cJSON_GetArrayItem (cJSON *array, int item)
cJSON * cJSON_GetObjectItem (cJSON *object, const char *string)
const char * cJSON_GetErrorPtr ()
cJSON * cJSON_CreateNull ()
cJSON * cJSON_CreateTrue ()
cJSON * cJSON_CreateFalse ()
cJSON * cJSON_CreateBool (int b)
cJSON * cJSON_CreateNumber (double num)
cJSON * cJSON_CreateString (const char *string)
cJSON * cJSON_CreateArray ()
cJSON * cJSON_CreateObject ()
cJSON * cJSON_CreateIntArray (int *numbers, int count)
cJSON * cJSON_CreateFloatArray (float *numbers, int count)
cJSON * cJSON_CreateDoubleArray (double *numbers, int count)
cJSON * cJSON_CreateStringArray (const char **strings, int count)
void cJSON_AddItemToArray (cJSON *array, cJSON *item)
void cJSON_AddItemToObject (cJSON *object, const char *string, cJSON *item)
void cJSON_AddItemReferenceToArray (cJSON *array, cJSON *item)
void cJSON_AddItemReferenceToObject (cJSON *object, const char *string, cJSON *item)
cJSON * cJSON_DetachItemFromArray (cJSON *array, int which)
void cJSON_DeleteItemFromArray (cJSON *array, int which)
cJSON * cJSON_DetachItemFromObject (cJSON *object, const char *string)
void cJSON_DeleteItemFromObject (cJSON *object, const char *string)
void cJSON_ReplaceItemInArray (cJSON *array, int which, cJSON *newitem)
void cJSON_ReplaceItemInObject (cJSON *object, const char *string, cJSON *newitem)
Define Documentation
#define cJSON_AddFalseToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateFalse())
#define cJSON_AddNullToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateNull())
#define cJSON_AddNumberToObject (object, name, n) cJSON_AddItemToObject(object, name, cJSON_CreateNumber(n))
#define cJSON_AddStringToObject (object, name, s) cJSON_AddItemToObject(object, name, cJSON_CreateString(s))
#define cJSON_AddTrueToObject (object, name) cJSON_AddItemToObject(object, name, cJSON_CreateTrue())
#define cJSON_Array 5
Referenced by cJSON_CreateArray(), parse_array(), and print_value().
#define cJSON_False 0
Referenced by cJSON_CreateBool(), cJSON_CreateFalse(), parse_value(), and print_value().
#define cJSON_IsReference 256
Referenced by cJSON_Delete(), and create_reference().
#define cJSON_NULL 2
Referenced by cJSON_CreateNull(), parse_value(), and print_value().
#define cJSON_Number 3
Referenced by cJSON_CreateNumber(), parse_number(), and print_value().
#define cJSON_Object 6
Referenced by cJSON_CreateObject(), parse_object(), and print_value().
#define cJSON_String 4
Referenced by cJSON_CreateString(), parse_string(), and print_value().
#define cJSON_True 1
Referenced by cJSON_CreateBool(), cJSON_CreateTrue(), parse_value(), and print_value().
Typedef Documentation
typedef struct cJSON cJSON
typedef struct cJSON_Hooks cJSON_Hooks
Function Documentation
void cJSON_AddItemReferenceToArray (cJSON * array, cJSON * item)
void cJSON_AddItemReferenceToObject (cJSON * object, const char * string, cJSON * item)
void cJSON_AddItemToArray (cJSON * array, cJSON * item)
Referenced by cJSON_AddItemReferenceToArray(), and cJSON_AddItemToObject().
void cJSON_AddItemToObject (cJSON * object, const char * string, cJSON * item)
Referenced by cJSON_AddItemReferenceToObject().
cJSON* cJSON_CreateArray ()
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), cJSON_CreateIntArray(), and cJSON_CreateStringArray().
cJSON* cJSON_CreateBool (int b)
cJSON* cJSON_CreateDoubleArray (double * numbers, int count)
cJSON* cJSON_CreateFalse ()
cJSON* cJSON_CreateFloatArray (float * numbers, int count)
cJSON* cJSON_CreateIntArray (int * numbers, int count)
cJSON* cJSON_CreateNull ()
cJSON* cJSON_CreateNumber (double num)
Referenced by cJSON_CreateDoubleArray(), cJSON_CreateFloatArray(), and cJSON_CreateIntArray().
cJSON* cJSON_CreateObject ()
cJSON* cJSON_CreateString (const char * string)
Referenced by cJSON_CreateStringArray().
cJSON* cJSON_CreateStringArray (const char ** strings, int count)
cJSON* cJSON_CreateTrue ()
void cJSON_Delete (cJSON * c)
Referenced by cJSON_Delete(), cJSON_DeleteItemFromArray(), cJSON_DeleteItemFromObject(), cJSON_Parse(), cJSON_ReplaceItemInArray(), and createTableFromBIXIES().
void cJSON_DeleteItemFromArray (cJSON * array, int which)
void cJSON_DeleteItemFromObject (cJSON * object, const char * string)
cJSON* cJSON_DetachItemFromArray (cJSON * array, int which)
Referenced by cJSON_DeleteItemFromArray(), and cJSON_DetachItemFromObject().
cJSON* cJSON_DetachItemFromObject (cJSON * object, const char * string)
Referenced by cJSON_DeleteItemFromObject().
cJSON* cJSON_GetArrayItem (cJSON * array, int item)
Referenced by addContent().
int cJSON_GetArraySize (cJSON * array)
Referenced by addAttributes(), addContent(), and constructSymbolTable().
const char* cJSON_GetErrorPtr ()
cJSON* cJSON_GetObjectItem (cJSON * object, const char * string)
void cJSON_InitHooks (cJSON_Hooks * hooks)
cJSON* cJSON_Parse (const char * value)
Referenced by createTableFromBIXIES().
char* cJSON_Print (cJSON * item)
char* cJSON_PrintUnformatted (cJSON * item)
void cJSON_ReplaceItemInArray (cJSON * array, int which, cJSON * newitem)
Referenced by cJSON_ReplaceItemInObject().
void cJSON_ReplaceItemInObject (cJSON * object, const char * string, cJSON * newitem)