BIXIE: decoding.h File Reference
decoding.h File Reference
Functions
int decodeIPType (char **out, byte **bufferPos)
int decodeInt (char **out, byte **bufferPos)
int decodeString (char **out, byte **bufferPos)
int decodeVarintToCInt (int *out, byte **bufferPos)
int decodeIntOrEmpty (char **out, byte **bufferPos)
int decodeSignednessType (char **out, byte **bufferPos)
int decodeByteorderType (char **out, byte **bufferPos)
int decodeCharType (char **out, byte **bufferPos)
int decodeCharsType (char **out, byte **bufferPos)
int decodeBoolean (char **out, byte **bufferPos)
int decodeEmpty (char **out, byte **bufferPos)
Function Documentation
int decodeBoolean (char ** out, byte ** bufferPos)
Decode the simple type "boolean"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeByteorderType (char ** out, byte ** bufferPos)
Decode the simple type "byteorderType"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeCharsType (char ** out, byte ** bufferPos)
Decode the simple type "charsType"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeCharType (char ** out, byte ** bufferPos)
Decode the simple type "charType"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeEmpty (char ** out, byte ** bufferPos)
Decode the simple type "empty"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeInt (char ** out, byte ** bufferPos)
Decode the simple type "Int"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
Referenced by decodeCharsType(), and decodeString().
int decodeIntOrEmpty (char ** out, byte ** bufferPos)
Decode the simple type "IntOrEmpty"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeIPType (char ** out, byte ** bufferPos)
Decode the simple type "IPType"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeSignednessType (char ** out, byte ** bufferPos)
Decode the simple type "signednessType"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeString (char ** out, byte ** bufferPos)
Decode the simple type "String"
Parameters:
out The out parameter, returning a string contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
int decodeVarintToCInt (int * out, byte ** bufferPos)
Decode the simple type "Variant"
Parameters:
out The out parameter, returning a int contaning the decoded value
bufferPos The buffer containing the BIXIE encoded data
Returns:
Returns and integer error flag if an error occurred
Referenced by decodeBIXIEToAST(), parseAttributes(), and parseNode().