BIXIE: encoding.h File Reference
encoding.h File Reference
#include "compiler.h"
Functions
int encodeIPType (char *in, byte **out, int *outlen)
int encodeInt (char *ins, byte **out, int *outlen)
int encodeString (char *in, byte **out, int *outlen)
int encodeIntOrEmpty (char *ins, byte **out, int *outlen)
int encodeSignednessType (char *in, byte **out, int *outlen)
int encodeByteorderType (char *in, byte **out, int *outlen)
int encodeCharType (char *in, byte **out, int *outlen)
int encodeCharsType (char *in, byte **out, int *outlen)
int encodeEmpty (char *in, byte **out, int *outlen)
int encodeBoolean (char *in, byte **out, int *outlen)
int encodeCIntValue (int, byte **out, int *size)
Function Documentation
int encodeBoolean (char * in, byte ** out, int * outlen)
int encodeByteorderType (char * in, byte ** out, int * outlen)
int encodeCharsType (char * in, byte ** out, int * outlen)
int encodeCharType (char * in, byte ** out, int * outlen)
int encodeCIntValue (int , byte ** out, int * size)
Referenced by encodeAttributes(), encodeContent(), encodeElement(), and encodeTrailingSequence().
int encodeEmpty (char * in, byte ** out, int * outlen)
int encodeInt (char * ins, byte ** out, int * outlen)
Encode the simple type "int"
Parameters:
ins In parameter containing the value to be encoded as a string
out The out parameter, returning a byte buffer contaning the encoded value
outlen The length of the encoded data in parameter out
Returns:
Returns and integer error flag if an error occurred
Referenced by encodeCharsType(), and encodeString().
int encodeIntOrEmpty (char * ins, byte ** out, int * outlen)
int encodeIPType (char * in, byte ** out, int * outlen)
Encode the simple type "IPType"
Parameters:
in In parameter containing the value to be encoded as a string
out The out parameter, returning a byte buffer contaning the encoded value
outlen The length of the encoded data in parameter out
Returns:
Returns and integer error flag if an error occurred
int encodeSignednessType (char * in, byte ** out, int * outlen)
int encodeString (char * in, byte ** out, int * outlen)