BIXIE: xmlwriter.c File Reference
xmlwriter.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "xmlwriter.h"
Defines
#define XML_BUFFER 209715200
Functions
static char * writeElementToXML (element_t *element, char *xml)
static void freeASTElement (element_t *element)
char * writeASTToXML (element_t *ast)
Define Documentation
#define XML_BUFFER 209715200
Referenced by writeASTToXML().
Function Documentation
static void freeASTElement (element_t * element) [static]
Will free an element of the AST
Parameters:
element The element to be freed
Returns:
Referenced by writeElementToXML().
char* writeASTToXML (element_t * ast)
Write an AST as XML
Parameters:
ast The AST to be written as XML
Returns:
The XML buffer containing the AST written as XML. This string is null terminated.
Referenced by decodeBIXIEToXML().
static char * writeElementToXML (element_t * element, char * xml) [static]
Write a single element of an AST as XML
Parameters:
element The element to be written as XML
xml The XML buffer to contain the written XML of the element
Returns:
The xml buffer with the new XML appended
Referenced by writeASTToXML().