BIXIE: bixieparser.c File Reference
bixieparser.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "symboltable.h"
#include "compilerdefs.h"
#include "bixieparser.h"
Functions
static void parseNode (element_t *node, byte **bufferPos, symbolTable_t *symbolTable)
static char * readSimpleType (int ID, symbolTable_t *symbolTable, byte **bufferPos)
static void parseAttributes (element_t *node, byte **bufferPos, symbolTable_t *symbolTable, elementTable_t *elementTable)
element_t * decodeBIXIEToAST (byte *bixieBuffer, symbolTable_t *symbolTable)
Function Documentation
element_t* decodeBIXIEToAST (byte * bixieBuffer, symbolTable_t * symbolTable)
Decode a buffer of BIXIE data into an AST
Parameters:
bixieBuffer The buffer full of BIXIE data
symbolTable The symbol table assciated with the BIXIE data
Returns:
The AST constructed from the BIXIE data
Referenced by decodeBIXIEToXML().
static void parseAttributes (element_t * node, byte ** bufferPos, symbolTable_t * symbolTable, elementTable_t * elementTable) [static]
Parse the attributes of an element
Parameters:
node The node which attributes to be parsed
bufferPos The buffer of BIXIE data
symbolTable The symbol table assciated with the BIXIE data
elementTable The element table associated with the type of the current element
Returns:
Referenced by parseNode().
static void parseNode (element_t * node, byte ** bufferPos, symbolTable_t * symbolTable) [static]
Parse a node from the BIXIE data
Parameters:
node The node to return when parsed
bufferPos The buffer of BIXIE data
symbolTable The symbol table assciated with the BIXIE data
Returns:
Referenced by decodeBIXIEToAST().
static char * readSimpleType (int ID, symbolTable_t * symbolTable, byte ** bufferPos) [static]
Read the simple type from the buffer together with a type ID
Parameters:
ID The ID of a simple type
symbolTable The symbol table assciated with the BIXIE data
bufferPos The buffer of BIXIE data
Returns:
The simple type as a string
Referenced by parseAttributes(), and parseNode().