BIXIE: expatparser.c File Reference
expatparser.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <expat.h>
#include "expatparser.h"
#include "ast.h"
#include "symboltable.h"
Data Structures
struct parseStack_t
struct parseData_t
Defines
#define XML_FMT_INT_MOD "l"
#define STACK_BUFFER_SIZE 10
#define CONTENT_READ 1
#define CONTENT_NOT_READ 2
Functions
static void initStack (parseStack_t *stack, int bufferSize)
static void freeStackContent (parseStack_t *stack)
static element_t * popElement (parseStack_t *stack)
static element_t * topElement (parseStack_t *stack)
static void pushElement (parseStack_t *stack, element_t *element)
static void XMLCALL startElement (void *userData, const char *name, const char **atts)
static void XMLCALL endElement (void *userData, const char *name)
static void XMLCALL textHandler (void *userData, const XML_Char *s, int length)
static int countAttributes (const char **atts)
static void copyAttributes (element_t *element, const char **atts, int attributeCount)
static void setParent (element_t *element, element_t *topElement)
static void setRightSibling (element_t *element, element_t *lastPopped)
static void decorateAttributes (attribute_t *attributes, int attributeCount, elementTable_t *elementTable)
static void updateChildListOnParent (parseStack_t *stack, element_t *element, elementTable_t *elementTable)
element_t * parseXML (char *xml, int length, symbolTable_t symbolTable)
Define Documentation
#define CONTENT_NOT_READ 2
Referenced by startElement(), and textHandler().
#define CONTENT_READ 1
Referenced by endElement(), and textHandler().
#define STACK_BUFFER_SIZE 10
Referenced by parseXML().
#define XML_FMT_INT_MOD "l"
Referenced by parseXML().
Function Documentation
static void copyAttributes (element_t * element, const char ** atts, int attributeCount) [static]
Copies attributes from EXPAT into a element
Parameters:
element The element the attributes should be copied to
atts The attributes to be copied
attributeCount The number of attributes in parameter atts
Returns:
Referenced by startElement().
static int countAttributes (const char ** atts) [static]
Counts the number of attributes given by a pointer returned by EXPAT
Parameters:
atts The array of attributes to be counted
Returns:
The number of attributes in parameter atts
Referenced by startElement().
static void decorateAttributes (attribute_t * attributes, int attributeCount, elementTable_t * elementTable) [static]
Iterates over some attributes and decorates them with ID's from a element table
Parameters:
attributes The attributes to be iterated trough
attributeCount The amount of attributes
elementTable The element table which contains the IDs for the attributes
Referenced by startElement().
static void XMLCALL endElement (void * userData, const char * name) [static]
EXPAT handler function that is called every time it parses an element end tag
Parameters:
userData The user data carried on through the parsing
name The name of the element just parsed
Returns:
Referenced by parseXML().
static void freeStackContent (parseStack_t * stack) [static]
Frees all allocated memory used for a stack
Parameters:
stack The stack which memory will be freed
Returns:
Referenced by parseXML().
static void initStack (parseStack_t * stack, int bufferSize) [static]
Initiates a new stack and allocates memory
Parameters:
stack The stack to be initiated
bufferSize Size of the buffer needed to be allocated
Returns:
Referenced by parseXML().
element_t* parseXML (char * xml, int length, symbolTable_t symbolTable)
Starts a EXPAT parser on the given xml buffer. During the the parse it creates an abstract syntax tree and returns it when it is done.
Parameters:
xml The XML to be parsed
length The length of the XML to be parsed
symbolTable The symbol table generated from the associated BIXIES schema
Returns:
Returns the top element of the parsed XML
Referenced by encodeXMLToBIXIE().
static element_t * popElement (parseStack_t * stack) [static]
Pops the top element of a stack and returns it
Parameters:
stack The stack to be popped from
Returns:
The element which was popped off the stack
Referenced by endElement().
static void pushElement (parseStack_t * stack, element_t * element) [static]
Pushes a new element onto a stack
Parameters:
stack The stack to be pushed onto
element The element to be pushed onto the stack
Returns:
Referenced by startElement().
static void setParent (element_t * element, element_t * topElement) [static]
Sets the parent of the element if there is one
Parameters:
element The element to have its parent set
topElement The parent element of the element parameter
Returns:
Referenced by startElement().
static void setRightSibling (element_t * element, element_t * lastPopped) [static]
Checks if the last element popped of the stack should have its right sibling set to the current element
Parameters:
element The current element
lastPopped The last popped element of the stack
Referenced by startElement().
static void XMLCALL startElement (void * userData, const char * name, const char ** atts) [static]
EXPAT handler function that is called every time it parses an element start tag
Parameters:
userData The user data carried on through the parsing
name The name of the element about to be parsed
atts The attributes associated with the element
Returns:
Referenced by parseXML().
static void XMLCALL textHandler (void * userData, const XML_Char * s, int length) [static]
EXPAT Handler for all text that is not an element. It is called even at newlines between elements
Parameters:
userData The user data carried on through the parsing
s The string found in the input stream. This string is NOT zero terminated
length The length of parameter s
Returns:
Referenced by parseXML().
static element_t * topElement (parseStack_t * stack) [static]
Returns the top element of a stack
Parameters:
stack The stack to get the element from
Returns:
The top element of the stack, without popping it
Referenced by setParent(), startElement(), textHandler(), and updateChildListOnParent().
static void updateChildListOnParent (parseStack_t * stack, element_t * element, elementTable_t * elementTable) [static]
Increments one of the counts on a parent element's list of children
Parameters:
stack The stack containing elements
element The element containing children
elementTable The element table which contains the different element types
Returns:
Referenced by startElement().