BIXIE: symboltable.c File Reference
symboltable.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include "cJSON.h"
#include "symboltable.h"
#include "encoding.h"
#include "decoding.h"
Defines
#define SIMPLE_TABLE_SIZE 13
Functions
static char * getJSONFromFile (char *fileName)
static symbolTable_t constructSymbolTable (cJSON *jsonObjects)
static void addAttributes (cJSON *element, elementTable_t *elementTable, simpleTypeTable_t *simpleTypeTable)
static int getSimpleTypeID (simpleTypeTable_t *simpleTypeTable, cJSON *attributeType)
static void addContent (cJSON *element, elementTable_t *elementTable, symbolTable_t *symbolTable)
static void printElementTable (elementTable_t *elementTable)
symbolTable_t createTableFromBIXIES (char *fileName)
elementTable_t * getElementTableByName (symbolTable_t *symbolTable, char *name)
elementTable_t * getElementTableByID (symbolTable_t *symbolTable, int ID)
void freeSymbolTable (symbolTable_t *symbolTable)
int getSimpleTypeIDByAttributeID (elementTable_t *elementTable, int attributeID)
int getAttributeIndexByID (int ID, elementTable_t *elementTable)
Variables
static int(*)(char *, byte
**, int *) getEncodingFunctionByName (char *typeName)
static int(*)(char **, byte **) getDecodingFunctionByName (char *typeName)
int(*)(char *, byte **, int *) getEncodingFunctionByID (symbolTable_t *symbolTable, int ID)
int(*)(char **, byte **) getDecodingFunctionByID (symbolTable_t *symbolTable, int ID)
Define Documentation
#define SIMPLE_TABLE_SIZE 13
Referenced by constructSymbolTable(), and getSimpleTypeID().
Function Documentation
static void addAttributes (cJSON * elementChild, elementTable_t * elementTable, simpleTypeTable_t * simpleTypeTable) [static]
Add attributes from a JSON element to a element table
Parameters:
element A single JSON element
elementTable The element table to which the element belong
simpleTypeTable The table that holds the simple types
Returns:
Referenced by constructSymbolTable().
static void addContent (cJSON * element, elementTable_t * elementTable, symbolTable_t * symbolTable) [static]
Add content from a JSON element object to a element table
Parameters:
element A single JSON element
elementTable The element table to which the element belong
simpleTypeTable The table that holds the simple types
Returns:
Referenced by constructSymbolTable().
static symbolTable_t constructSymbolTable (cJSON * jsonObjects) [static]
Constructs a symbol table from BIXIES parsed in as JSON objects
Parameters:
jsonObjects The jsonObjects needed to construct the symbol table
Returns:
The symbol table
Referenced by createTableFromBIXIES().
symbolTable_t createTableFromBIXIES (char * fileName)
Creates a new symbol table from a BIXIES file
Parameters:
fileName The filename of a BIXIES schema to create the symbol table from
Returns:
The symbol table
Referenced by decodeFile(), and encodeFile().
void freeSymbolTable (symbolTable_t * symbolTable)
Referenced by decodeFile(), and encodeFile().
int getAttributeIndexByID (int ID, elementTable_t * elementTable)
Get the attribute ID based on a simple type ID and a element table
Parameters:
elementTable The element table associated with the current element
attributeID The simple type of the attribute
Returns:
The ID of the attribute
Referenced by parseAttributes().
elementTable_t* getElementTableByID (symbolTable_t * symbolTable, int ID)
Referenced by parseNode().
elementTable_t* getElementTableByName (symbolTable_t * symbolTable, char * name)
Searches through the symbol table for a subelement table with the given name
Parameters:
symbolTable The symbol table to search through
name The name of the element to find in the symbol table
Returns:
The specific element found by its name
Referenced by encodeElement(), and startElement().
static char * getJSONFromFile (char * fileName) [static]
Load JSON from a file into a buffer
Parameters:
fileName The filename of the JSON file containing the BIXIES schema
Returns:
The content of the file
Referenced by createTableFromBIXIES().
static int getSimpleTypeID (simpleTypeTable_t * simpleTypeTable, cJSON * attributeType) [static]
Returns a simple type ID based on the simpel type name in a JSON attribute type object
Parameters:
simpleTypeTable The table that holds the simple types
attributeType The type of the attribute
Returns:
The ID of the simple type in the simpleTypeTable
Referenced by addAttributes(), and addContent().
int getSimpleTypeIDByAttributeID (elementTable_t * elementTable, int attributeID)
Get the simple type ID based on an attribute ID
Parameters:
elementTable The element table associated with the current element
attributeID The ID of the attribute
Returns:
The simple type ID of the attribute
Referenced by parseAttributes().
static void printElementTable (elementTable_t * elementTable) [static]
Test print of an element table
Parameters:
elementTable The table of elements to be printed
Returns:
Variable Documentation
int(*)(char**, byte**) getDecodingFunctionByID(symbolTable_t *symbolTable, int ID)
Referenced by readSimpleType().
int(*)(char**, byte**) getDecodingFunctionByName(char *typeName) [static]
Get an decoding function given by a simpel type name
Parameters:
typeName The name of the decoding function
Returns:
Returns a function for decoding
Referenced by getSimpleTypeID().
int(*)(char*, byte**, int*) getEncodingFunctionByID(symbolTable_t *symbolTable, int ID)
Get an encoding function given by a simpel type ID
Parameters:
symbolTable The symbol table
ID The id of the simple type
Returns:
Returns a function for encoding
Referenced by encodeAttributes(), and encodeContent().
int(*)(char*, byte**, int*) getEncodingFunctionByName(char *typeName) [static]
Get an encoding function given by a simpel type name
Parameters:
typeName The name of the decoding function
Returns:
Returns a function for decoding
Referenced by getSimpleTypeID().