BIXIE: symboltable.h File Reference
symboltable.h File Reference
#include <stdlib.h>
#include "cJSON.h"
#include "compilerdefs.h"
Data Structures
struct simpleTypeFunctions_t
struct simpleTypeTable_t
struct attributeEntry_t
struct elementEntries_t
struct elementTable_t
struct symbolTable_t
Functions
symbolTable_t createTableFromBIXIES (char *fileName)
elementTable_t * getElementTableByName (symbolTable_t *symbolTable, char *name)
elementTable_t * getElementTableByID (symbolTable_t *symbolTable, int ID)
void freeSymbolTable (symbolTable_t *symbolTable)
int getSimpleTypeIDByAttributeID (elementTable_t *elementTable, int attributeID)
int getAttributeIndexByID (int ID, elementTable_t *elementTable)
Variables
int(*)(char *, byte **, int *) getEncodingFunctionByID (symbolTable_t *symbolTable, int ID)
int(*)(char **, byte **) getDecodingFunctionByID (symbolTable_t *symbolTable, int ID)
Function Documentation
symbolTable_t createTableFromBIXIES (char * fileName)
Creates a new symbol table from a BIXIES file
Parameters:
fileName The filename of a BIXIES schema to create the symbol table from
Returns:
The symbol table
Referenced by decodeFile(), and encodeFile().
void freeSymbolTable (symbolTable_t * symbolTable)
Referenced by decodeFile(), and encodeFile().
int getAttributeIndexByID (int ID, elementTable_t * elementTable)
Get the attribute ID based on a simple type ID and a element table
Parameters:
elementTable The element table associated with the current element
attributeID The simple type of the attribute
Returns:
The ID of the attribute
Referenced by parseAttributes().
elementTable_t* getElementTableByID (symbolTable_t * symbolTable, int ID)
Referenced by parseNode().
elementTable_t* getElementTableByName (symbolTable_t * symbolTable, char * name)
Searches through the symbol table for a subelement table with the given name
Parameters:
symbolTable The symbol table to search through
name The name of the element to find in the symbol table
Returns:
The specific element found by its name
Referenced by encodeElement(), and startElement().
int getSimpleTypeIDByAttributeID (elementTable_t * elementTable, int attributeID)
Get the simple type ID based on an attribute ID
Parameters:
elementTable The element table associated with the current element
attributeID The ID of the attribute
Returns:
The simple type ID of the attribute
Referenced by parseAttributes().
Variable Documentation
int(*)(char**, byte**) getDecodingFunctionByID(symbolTable_t *symbolTable, int ID)
int(*)(char*, byte**, int*) getEncodingFunctionByID(symbolTable_t *symbolTable, int ID)